"""rename department

Revision ID: 40da5aed33b4
Revises: df53332d5db0
Create Date: 2024-01-07 14:06:19.179960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40da5aed33b4"
down_revision = "df53332d5db0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
